### ISSUE TITLE
Import error 

### ISSUE THREAD

**Issue by Franco98404** [jpsandovaln/ATLatam2#8]
This is the line where we have the error. @lcarrietas

https://github.com/jpsandovaln/ATLatam2/blob/441fe94ccfb5c29363569cb14c4c40b3795e02c5/CONVERT_SERVICE/convert_service/convert_service/views.py#L24

**Comment by lcarrietas** [comment]
Django server was already UP. And after trying the import then the error [**ValueError: attempted relative import beyond top-level package**] shows up.

We tried using the folders as python packages and the error persists.
